### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by Nick-Sun1018** [yenanjing/mmEgo#2]
Your work in this repo is excellent, could you please release your paper so that I could further understand the key point of your idea, thank you!

**Comment by yenanjing** [comment]
> Your work in this repo is excellent, could you please release your paper so that I could further understand the key point of your idea, thank you!

I don't know why the paper has not been published. Attached is my paper and enjoy reading please.
[Sensys_23_Egocentric_Human_Pose_Estimation_using_Head_mounted_mmWave_Radar__Final_.pdf](https://github.com/yenanjing/mmEgo/files/13750770/Sensys_23_Egocentric_Human_Pose_Estimation_using_Head_mounted_mmWave_Radar__Final_.pdf)

**Comment by Nick-Sun1018** [comment]
> > Your work in this repo is excellent, could you please release your paper so that I could further understand the key point of your idea, thank you!
> 
> I don't know why the paper has not been published. Attached is my paper and enjoy reading please. [Sensys_23_Egocentric_Human_Pose_Estimation_using_Head_mounted_mmWave_Radar__Final_.pdf](https://github.com/yenanjing/mmEgo/files/13750770/Sensys_23_Egocentric_Human_Pose_Estimation_using_Head_mounted_mmWave_Radar__Final_.pdf)

Thanks!
